// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthUsecases is an autogenerated mock type for the AuthUsecases type
type AuthUsecases struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, phone, password
func (_m *AuthUsecases) Login(ctx context.Context, phone string, password string) (string, int64, error) {
	ret := _m.Called(ctx, phone, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, int64, error)); ok {
		return rf(ctx, phone, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, phone, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) int64); ok {
		r1 = rf(ctx, phone, password)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, phone, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAuthUsecases creates a new instance of AuthUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecases {
	mock := &AuthUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
