// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthRepositories is an autogenerated mock type for the AuthRepositories type
type AuthRepositories struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx
func (_m *AuthRepositories) Login(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthRepositories creates a new instance of AuthRepositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepositories {
	mock := &AuthRepositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
