// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SnowflakeManager is an autogenerated mock type for the SnowflakeManager type
type SnowflakeManager struct {
	mock.Mock
}

// GenerateID provides a mock function with given fields:
func (_m *SnowflakeManager) GenerateID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// NewSnowflakeManager creates a new instance of SnowflakeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnowflakeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnowflakeManager {
	mock := &SnowflakeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
